### PR TITLE
[Proposal] Type renames and naming convention

### PR DESCRIPTION
**Pull request by andreincu**
⚠️ This pull request contains breaking changes due to name changes of the properties. For example: `PageNode.pages` became `PageNode.children` for consistency.

⚠️ This is also incomplete because I rushed, seeing that you're pushing new changes pretty often. I want to avoid falling too far behind or spending time in vain.

### Why the following proposal
1. The current names are too long due to the repetition of the word "Penpot" everywhere.
1. As a developer, you might be aware of the importance of having a naming convention when you're working in a team. Such a convention will offer predictability in the long run and will help avoid unnecessary breaking changes due to lack of clarity.
2. This proposal will also increase the chance for people to migrate to Penpot, as it is similar to Figma's API. There will be no need to learn a new language to create Penpot plugins.

### Naming convention proposal
1. Use {Name + "Node"} for new node entities. e.g. ComponentNode or InstanceNode.
2. Use {Name + "Node" + "Mixin"} for node-related properties mixins. E.g. FrameNodeMixin or TextNodeMixin
3. Use {Name + "Mixin"} for properties mixins. E.g. GridLayoutMixin or FlexLayoutMixin.
4. Additional, if there is a minimum required mixin, then it can be called {"Minimal" + MixinName}
5. Constant values to be written with uppercase. E.g.: type: "LINEAR" | "RADIAL".

Right now it's a bit messy, especially with properties. For example, PenpotLayoutChildProperties versus PenpotCommonLayout.

The context is also important: we're already inside a Penpot file, so there is no need to repeat "Penpot" everywhere. Repeating "Penpot" makes everything longer without adding any value.

### CODE REVIEW

**Comment by andreincu** [comment]
There are a few leftover items that I didn't manage to change.
1. Not all `SceneNode` nodes have to inherit all the methods, especially the text-related ones. Therefore, it is required to break the properties into smaller Mixins. For example, `TextNodeMixin` should be inherited only by the `TextNode`, and not by `FrameNode`. 
Similarly, `TextNode` doesn't need the properties specific to a `FrameNode`, such as `FlexLayoutMixin` or `GridLayoutMixin`, because these properties will not exist on the `TextNode`, but on its `.parent` node.
2. I haven't changed all the documentation-related information; I'll do that if the feedback from your side is positive.

**Comment by cocotime** [comment]
Hi @andreincu,

Thank you for your contribution and the valuable feedback you have provided. We genuinely appreciate the effort and thought you have put into this.

After careful consideration, we have decided not to accept your merge request at this time. While we recognize the merits of your suggestions and see potential for incorporating some of your ideas into the API, we have decided to maintain our current naming conventions. We understand that some users might prefer a naming structure similar to Figma's, but we believe our chosen naming conventions best suit our needs and objectives.

We appreciate your understanding and hope you will continue to share your insights with us.

Best regards,
Marina

**Comment by cocotime** [comment]
Hi @andreincu,

Thank you for your contribution and the valuable feedback you have provided. We genuinely appreciate the effort and thought you have put into this.

After careful consideration, we have decided not to accept your merge request at this time. While we recognize the merits of your suggestions and see potential for incorporating some of your ideas into the API, we have decided to maintain our current naming conventions. We understand that some users might prefer a naming structure similar to Figma's, but we believe our chosen naming conventions best suit our needs and objectives.

We appreciate your understanding and hope you will continue to share your insights with us.

Best regards,
Marina

**Comment by andreincu** [comment]
Hi @cocotime ,

Thank you for taking the time to review everything related to this request.

It's a bit disappointing that you decided not to streamline the migration from the Figma API to the Penpot API, but you likely know better what your audience needs.

I might just not be among them. 🤷‍♂️

Good luck! 🎉

**Pull request closed without merging**
